language: node_js
node_js: 
 - "8"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=Alejo721_micalc -Dsonar.projectKey=alejo721 -Dsonar.sources='./app' -X